---
- hosts: all
  become: True
  tasks:
    - name: Install apache server
      apt:
        name: "apache2"
        state: "present"

    - name: Enable apache on reboot
      service:
        name: apache2
        state: started
        enabled: True

    - name: Install git
      apt:
        name: git
        state: present

    - name: Deploy website from git
      git:
        repo: https://github.com/nick-kadhao/css.temp.git
        dest: /var/www/html/
    - name: restart apache
      service:
        name: apache2
        state: restarted

...

